const CONFIG = {
    titleWeb: "tới em <3",
    introTitle: 'yêu anh không',
    introDesc: `Đằng sau chữ yêu đây là thương`,
    btnIntro: '^^Hảifò^^',
    title: 'yêu anh đi bố anh gỉàu 🥰',
    desc: 'dù anh nghiện =)) ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'yêu bạn <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối mai 7h, anh qua đón đi xoạc nha.',
    btnAccept: 'Oki lunnnn <3',
    messLink: 'https://www.facebook.com/'
